version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=development
      - PORT=3002
    command:
      sh -c 'yarn && yarn dev'      

    